leios: Restricts only to required cardano-ledger libs
Otherwise we can't compile due to

error: builder for '/nix/store/jvg1kv1bjbl1m88qm02hdyq460pxg8gc-cardano-ledger-binary-lib-testlib-1.6.0.0.drv' failed with exit code 1;
       last 10 log lines:
       >         ‘withGenTerm cddlData (Cuddle.Name ruleName)’
       >       In the expression:
       >         withGenTerm cddlData (Cuddle.Name ruleName)
       >           $ roundTripAnnExample lbl version version trip
       >     |
       > 130 |           withGenTerm cddlData (Cuddle.Name ruleName) $
       >     |                                 ^^^^^^^^^^^^^^^^^^^^