locli: disable on windows (thank you a lot @hamishmack for analysis and solution !)
This fixes:

$ nix build .#hydraJobs.linux.windows.cardano-api --show-trace

...

Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: Win32-network-0.1.0.0 (user goal)
[__1] trying: base-4.14.3.0/installed-4.14.3.0 (dependency of Win32-network)
[__2] trying: locli-1.29 (user goal)
[__3] next goal: unix (dependency of locli)
[__3] rejecting: unix-2.7.2.2, unix-2.7.2.1, unix-2.7.2.0 (library is not
buildable in the current environment, but it is required by locli)
[__3] rejecting: unix-2.7.1.0 (conflict: base==4.14.3.0/installed-4.14.3.0,
unix => base>=4.5 && <4.9)
[__3] skipping: unix-2.7.0.1, unix-2.7.0.0, unix-2.6.0.1, unix-2.6.0.0,
unix-2.5.1.1, unix-2.5.1.0, unix-2.5.0.0, unix-2.4.2.0, unix-2.4.1.0,
unix-2.4.0.2, unix-2.4.0.1, unix-2.4.0.0, unix-2.3.2.0, unix-2.3.1.0,
unix-2.3.0.0, unix-2.2.0.0, unix-2.0 (has the same characteristics that caused
the previous version to fail: excludes 'base' version 4.14.3.0)
[__3] fail (backjumping, conflict set: base, locli, unix)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, unix, locli, Win32-network
Try running with --minimize-conflict-set to improve the error message.

error: attribute 'cardano-api' missing

       at /nix/store/zjsyf2bh23q5cxrlbdj0yx7ibr3fxy27-source/flake.nix:172:49: